[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-1w3j-dark
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-1w3j-dark
GtkTheme=oomox-1w3j-dark
IconTheme=oomox-1w3j-dark
MetacityTheme=oomox-1w3j-dark
