#!/bin/sh
#Generated with love at Sun Jan 27 09:35:19 2019 by JetBrains Toolbox 1.8.3868 (May 25 2018)

"/home/iqbal/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.5107.22/bin/pycharm.sh" "$@"

