#!/bin/sh
#Generated with love at Tue Jan 15 08:44:17 2019 by JetBrains Toolbox 1.12.4481 (Nov  9 2018)

"/home/iqbal/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.5107.22/bin/pycharm.sh" "$@"

