#@IgnoreInspection BashAddShebang
# Shell variables
# Generated by 'wal'
wallpaper='~/1w3j/wallpapers/OMEN_by_HP.jpg'

# Special
background='#0C0909'
foreground='#e99499'
cursor='#e99499'

# Colors
color0='#0C0909'
color1='#AE1914'
color2='#9E231F'
color3='#B22828'
color4='#C81A1A'
color5='#D1292D'
color6='#DC282E'
color7='#e99499'
color8='#a3676b'
color9='#AE1914'
color10='#9E231F'
color11='#B22828'
color12='#C81A1A'
color13='#D1292D'
color14='#DC282E'
color15='#e99499'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
