#!/bin/sh
#Generated with love at Wed Sep 19 21:39:52 2018 by JetBrains Toolbox 1.8.3868 (May 25 2018)

"/home/iqbal/.local/share/JetBrains/Toolbox/apps/datagrip/ch-0/182.4505.23/bin/datagrip.sh" "$@"

