#!/bin/sh
#Generated with love at Tue Jan 15 08:44:17 2019 by JetBrains Toolbox 1.12.4481 (Nov  9 2018)

"/home/iqbal/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/182.4892.16/bin/phpstorm.sh" "$@"

