#!/bin/sh
#Generated with love at Thu Aug 23 21:50:09 2018 by JetBrains Toolbox 1.8.3868 (May 25 2018)

"/home/iqbal/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/182.4129.32/bin/webstorm.sh" "$@"

